### PR TITLE
Add single media select option to content type

### LINKED ISSUE #451: [MediaBundle] Single Media select
<a href="https://github.com/wachterjohannes"></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluMediaBundle/issues/64

needed for excerpt icon

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #451 |
| License | MIT |
#### What's in this PR?

Add single media select to media seleciton content type
#### Example Usage

``` xml
        <property name="media" type="media_selection">
            <meta>
                <title lang="en">Media</title>
                <title lang="de">Media</title>
            </meta>
            <params>
                <param name="single" value="true" />
            </params>
        </property>
```

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot if this is ok would be great in 1.3 (:

**Comment by danrot** [comment]
Actually the conclusion from #451 (at least for me 😄) was that we would implement a separate content type, for two reasons:

* The content type also should look different
* The content type should not return an array to the twig template

For the same reason I've implemented a `single_select` and `multiple_select` content type. IMO changing the options should not break anything, but if we want to pass a single image instead of an array to the twig template it would change its behavior significantly.

What do others think about this? /cc @wachterjohannes @chirimoya

**Comment by alexander-schranz** [comment]
@danrot The overlay looks different and no array is given to the twig template :)

**Comment by danrot** [comment]
Not only the overlay should be looking different, and that an array is passed to the template even if only one image is selectable is the exact strange thing for me.

**Comment by alexander-schranz** [comment]
@danrot as said in the twig template its no array: https://github.com/alexander-schranz/sulu/blob/5f91cbed061ebcb8ecde436220d56fb12abcc38f/src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php#L173

**Comment by danrot** [comment]
Ok, but that means that changing a parameter in a property breaks existing templates, which I would like to avoid.

**Comment by alexander-schranz** [comment]
@danrot  Would it ok for you to extend the `single_media_selection` class from the current media selection content type class?

**Comment by danrot** [comment]
Yeah, would be better IMO.

**Comment by alexander-schranz** [comment]
@chirimoya How we should save the data in the new content type?

Currently it is an array of ids:

```json
{
   displayOptions:
   ids: [
       1
   ]
}
```

For single this would maybe make more sense:

```json
{
   displayOptions:
   id: 1
}
```


The disadvantage of switching how the data is stored that it is not easy for exist project to switch from `media_selection` to `single_media_selection` without losing data.

**Comment by chirimoya** [comment]
```json
{
   displayOptions:
   id: 1
}
````

**Comment by andrewjt71** [comment]
Please ignore my PR approval, I have too many windows open and approved the wrong PR

**Comment by man-andy** [comment]
what is the status on this?

**Comment by danrot** [comment]
@man-andy The last changes we've discussed were not built into this PR, because nobody continued to work on it 😢

**Comment by alexander-schranz** [comment]
closed because this feature will not be implemented in 1.x only in 2.x which react UI.

**Pull request closed without merging**
