### PR TITLE
Fixed rerender review if html is the same

### LINKED ISSUE #3540: Live Preview reloads too often and not fully
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.3
| Browser Version | Google Chrome 61.0.3163.100

#### Actual Behavior

At first:
If you open a page on backend (or reload it) the website will be shown on the live preview window on right side. After all elements on left side (contents) are loaded, the live preview window will make a reload again.

If you take a look to the XHR requests, the second `admin` request will shown this message:
```
{"handler":"sulu_preview.preview","message":{"command":"update-context","webspaceKey": ...
```

At second:
If you reload the preview window, the page will be refreshed. But the JS will be initialized again - without removing the previous instance.
If you are defining global JS elements, these are duplicated.

#### Expected Behavior

The live preview should be loaded at once - not twice. It is a performance issue.
Also the whole page should be reloaded - to solve the issue with duplicated JS elements.

#### Steps to Reproduce

1. Open a page on backend. 
2. Set a breakpoint to the own JS file.
3. Reload the page
4. Now the breakpoint should be triggered twice.
5. Check the XHR request which was triggered and take a look to the message of the second one.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3540
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

These PR fixes avoid re-rendering the same HTML on the start of the preview.

#### Why?

This happens because the preview will be started (which returns the whole HTML) and afterward the update-context will be called (which returns also the whole HTML). This lead into a double complete rendering of the preview on start.

### CODE REVIEW

**Comment by danrot** [comment]
Any idea why the tests are failing? Current master seems to be fine...

**Comment by danrot** [comment]
And if the `update-context` is updating the html anyway, why should it be returned by `start` in the first place? This way we still receive the relatively big response two times...

**Comment by wachterjohannes** [comment]
@danrot I think I the tests were run against develop because I have changed the base afterward - I will restart them.

**Comment by wachterjohannes** [comment]
@danrot yes that's right - this could be done more efficient but this requires a bigger refactoring - because at this place cannot see if the template has changed or it is the initial rendering.

**Comment by danrot** [comment]
Merged, the other thing is something we should keep in mind for Sulu 2.0.

**Pull request merged**
