### PR TITLE
Add Twig main blocks to be able to use inheritance

### PR DESCRIPTION
**Pull request by gisostallenberg**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | N/A
| Related issues/PRs | N/A
| License | MIT
| Documentation PR | N/A

#### What's in this PR?

Added Twig blocks to allow inheritance

#### Why?

It will allow to add additional elements and buttons to the login and admin interface.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@gisostallenberg thanks for contribution :) i have 2 little things "cavil". Would you please add a changelog line (`CHANGELOG.md`)? And also indent the content of the block with additional 4 spaces.

**Comment by gisostallenberg** [comment]
Sure I will add an change log item. Label ENHANCEMENT?
How about indentation in https://github.com/sulu/sulu/pull/3849/files#diff-ebdfa64e0ecc5d0b1032966504a07ffdR16, I copied that style

**Comment by wachterjohannes** [comment]
yes `ENHANCEMENT` is good. Hmm your right - you can leave it as it is

**Comment by wachterjohannes** [comment]
@gisostallenberg thanks - i will wait for the tests and then merge it! you can expect a release by the next week!

**Comment by gisostallenberg** [comment]
@wachterjohannes can you restart the Travis build?

**Comment by wachterjohannes** [comment]
@gisostallenberg now its green and merged :)

**Pull request merged**
