### PR TITLE
Add CI lint container in different environments

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes -
| Related issues/PRs | #-
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Lint container in different environments.

#### Why?

Currently it seems linting failed on prod env on skeleton. To avoid this we should also lint this in sulu/sulu so we get feedback as soon as possible when sulu/sulu container is not correct in an environment.

### CODE REVIEW

**Comment by danrot** [comment]
:+1:, but would wait until symfony/symfony#37166 is fixed before merging that.

**Comment by alexander-schranz** [comment]
@danrot The Symfony issue is fixed now.

**Comment by danrot** [comment]
@alexander-schranz I restarted the tests, and they are failing for a different reason now. Can you check?

**Comment by danrot** [comment]
@alexander-schranz Is that good to merge now?

**Comment by alexander-schranz** [comment]
@danrot yes as  symfony/symfony#37166  is released this there should be no problems.

**Comment by danrot** [comment]
@alexander-schranz I am asking because I've updated the branch one more time, and so it is actually your task to merge it :slightly_smiling_face:

**Pull request merged**
