### PR TITLE
Store date directly after request

### PR DESCRIPTION
**Pull request by gisostallenberg**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | N/A
| Related issues/PRs | #2424
| License | MIT
| Documentation PR | N/A

#### What's in this PR?

A fix for an incidentally occurring issue in the CustomUrlControllerTest::testCGet test

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@gisostallenberg thanks for creating new PR i would be happy with adding this lines into the other one but this is much better (:

**Comment by gisostallenberg** [comment]
I see I need to rebase...

**Comment by wachterjohannes** [comment]
the tests are running i can merge this branch. but could you please rebase the other PR?

**Comment by gisostallenberg** [comment]
I will, thanks

**Pull request merged**
