### PR TITLE
Fix webspace name encoding problem with accents

### LINKED ISSUE #6827: Accents in webspace name render unicode in fulltext
| Q | A
| --- | ---
| Sulu Version | 2.5.1
| PHP Version | 8.1
| DB Version | MariaDB 10.7.3
| Browser Version | Firefox 105.0.1

# Actual Behavior

Using accents in the webspace name, render character unicode in fulltext:

Capture d’écran du 2022-09-28 11-12-27
**_Sulu 2.5.1_**

# Expected Behavior

Accents should be rendered correctly:

Capture d’écran du 2022-09-28 11-13-37
**_Sulu 2.5.0_**

# Steps to Reproduce

- Using Sulu 2.5.1 ;
- Add accents in a webspace name ;
- Connect to the admin, and go to "Webspaces" ;
- See the problem.

I also tested it with Chromium 105: same rendering problem.
I'm sure it is related to a change between Sulu 2.5.0 and 2.5.1, in the way that webspace name are serialized.

Thanks by advance :)

### PR DESCRIPTION
**Pull request by Jupi007**
| Q | A
| --- | ---
| Bug fix? |yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #6827
| Related issues/PRs | #6827
| License | MIT

#### What's in this PR?

This PR add the `JSON_UNESCAPED_UNICODE` flag to the `json_encode` function under `/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig`.

#### Why?

This fix a problem of unicode fulltext string in webspace name, when using accents.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@Jupi007 Thank you can you add also a test case. See https://github.com/sulu/sulu/pull/6714 as example.

**Comment by Jupi007** [comment]
Oh, you're right, sorry I have forgotten it.
I'll do it at once.

**Comment by Jupi007** [comment]
Done :)

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@Jupi007 Thank you!

**Pull request merged**
