### PR TITLE
Added Backbone to Sulu

### PR DESCRIPTION
**Pull request by 3rfan**
merge with https://github.com/massiveart/husky/pull/479/files

### CODE REVIEW

**Comment by chirimoya** [comment]
Check Backbone.js 1.2.0 compatibility

**Comment by chirimoya** [comment]
ping @3rfan ;-)

**Comment by webmozart** [comment]
What should we do about this? Close or merge?

**Comment by danrot** [comment]
Since we thought about removing backbone completely, this won't be merged.

**Pull request closed without merging**
