### PR TITLE
removed published icons from column navigation when page is ghost

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR includes a husky update, which removes the published and draft icons in the column navigation when the page is a ghost.

#### Why?

Because ghost pages do not really exist, and hence have no published state.

### CODE REVIEW

**Comment by danrot** [comment]
@marcelmoosbrugger After fixing this I have seen that the ckeditor still behaves wrong when a ghost page is assigned, it first shows it as unpublished, and after a reload as broken.

**Comment by danrot** [comment]
@chirimoya I've decided to adapt the column navigation, since it is hard to say if you want to have the required properties for the ghost or not, resp. it would be quite mixed (i.e. you get the title but not the published date, ...)

**Comment by marcelmoosbrugger** [comment]
@danrot What should be the behavior when adding a ghost page to the ck-editor? A gohst page does not really exist and therefore, the added link should always be marked as broken. Is this correct?

**Comment by danrot** [comment]
@marcelmoosbrugger I think the page does exist in a certain way, therefore I would go for marking the page in the ckeditor as unpublished.

**Pull request merged**
