### PR TITLE
Added support for multiple webspaces in the sitemap

### LINKED ISSUE #1129: Support multiple webspaces in the sitemap
A sitemap should support more then one webspace

### PR DESCRIPTION
**Pull request by alexander-schranz**
__Tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation
- [x] added changelog line

__Informations:__

| Q             | A
| ------------- | ---
| Fixed tickets | fixes #1129 
| BC Breaks     | none
| Doc           | none

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@alexander-schranz is this PR finished?

**Comment by wachterjohannes** [comment]
testcases missing (=

**Comment by alexander-schranz** [comment]
@wachterjohannes currently I'm not sure if we implement it this way. join the discussion here #1129

**Comment by webmozart** [comment]
Any update on this PR?

**Comment by alexander-schranz** [comment]
closed in favor of #2916

**Pull request closed without merging**
