### PR TITLE
Added option for single-markable in content-datasource

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/161
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR enhances the reusability of the component `content-datasource` if you use it as a single selection.

### CODE REVIEW

**Comment by danrot** [comment]
Actually I have only seen this component to be used with the possibility of selecting a single element. So why do we need to improve it in that way?

**Comment by wachterjohannes** [comment]
@danrot oh i have forgotten to link the PR in SuluArticleBundle https://github.com/sulu/SuluArticleBundle/pull/161

**Comment by wachterjohannes** [comment]
@danrot I have removed the option and set the options by default. In smart content and custom-urls, it also works this way.

**Comment by danrot** [comment]
That doesn't really work well for me... E.g. in the smart content you see a minus icon now, and if you click on it the other slide is shown again, but the same page is still selected.

**Comment by wachterjohannes** [comment]
I will move that to the article-bundle.

**Pull request closed without merging**
