### PR TITLE
Permit to extends easily the content repository

### PR DESCRIPTION
**Pull request by nicodmf**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Change all methods and properties from ContentRepository to protected.

#### Why?

The content repository is usefull but don't have all methods for all cases, change the methods and properties to protected permit to use it easily

#### Example Usage

~~~yaml
#Create a repository service extending the base contentRepository
services:
    site.sulu_content.content_repository: 
        class: Client\Bundle\APIBundle\Repository\ContentRepository
        arguments:
            - @sulu.phpcr.session
            - @sulu_document_manager.property_encoder
            - @sulu_core.webspace.webspace_manager
            - @sulu.content.localization_finder
            - @sulu.content.structure_manager
            - @sulu.util.node_helper
~~~

~~~php
<?php
namespace Client\Bundle\APIBundle\Repository;

/** Content repository which query content with sql2 statements. */
class ContentRepository extends \Sulu\Component\Content\Repository\ContentRepository
{
   //all you need
}

### CODE REVIEW

**Comment by danrot** [comment]
The problem with this solution is that we are not allowed to change any of the given behavior in any refactoring... What exactly do you need these changes for?

**Comment by nicodmf** [comment]
I need there methods :

- findChildsByPath with filters
- findByType with filters 

and maybe a complete exemple in the doc describing a document class creation would be better. 

But simpliest, i would prefer to use directly a sulu class with a pre-writen repository wich permit to allow complex query and return defined pages as they are configured in the xml definitions.

**Comment by danrot** [comment]
@nicodmf If you want to retrieve entire documents based on a query you should probably use the method `DocumentManager::createQuery` instead. There is also an open [Query Builder PR](https://github.com/sulu/sulu-document-manager/pull/60), which might suit your needs better.

**Comment by nicodmf** [comment]
Yes it's seems better, could we hope to see work soon. We are in a developement process which should ending in few week and this functionnality could be usefull.

**Comment by danrot** [comment]
You don't really have to wait for the query builder, for the moment you can still also use the `createQuery` function and write the SQL-2 queries on your own. Works exactly the same, has just less syntactic sugar 😃

**Comment by nicodmf** [comment]
OK, thank, if you agree i close this PR

**Pull request closed without merging**
