### PR TITLE
Show Webspace node on copy and move overlay. Fixes #2104

### LINKED ISSUE #2104: Pages can't be copied or moved to the first level of the column tree
| Q | A
| --- | ---
| Bug? | yes
| Version Used | 22579aa91105c5a844ee5a03ef656a007ae6a1f0
| New Feature? | no

#### Expected Behavior

It should be possible to copy or move pages to the first level of the content hierarchy (being the most left column in the content navigation). So there should be the column with webspaces as shown in this screenshot. (screenshot taken from the internal links content type)

image

#### Actual Behavior

The expected behavior is currently not possible, because the overlay which is opened after initiating the copy or move, doesn't allow to choose the webspace as parent. (the first column from the upper screenshot is missing)

image

#### Steps to Reproduce

1. Open the column tree (in the navigation `webspace > content`)
2. select a page
3. Click on the gear on the bottom of the column
4. Click on "Copy page" or "Move page"

#### Possible Solutions

The overlay should also show the column with the webspaces. I assume that setting the right id in the consecutive API call will just work, if not, that has also to be fixed.

### PR DESCRIPTION
**Pull request by akira28**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2104 
| License | MIT

#### What's in this PR?

This PR fixes #2104 , showing the webspace node on copy and move overlay.

#### To Do

- [x] Fix overlay css (now the webspace name is not completely visible)
- [x] Test every function using the same overlay
- [x] Submit dist file?

### CODE REVIEW

**Comment by akira28** [comment]
This is the css issue I'm referring to in the PR. To fix this the overlay.scss should be modified, but it doesn't seem to be available on the repo
screenshot 2016-06-29 14 35 20

**Comment by alexander-schranz** [comment]
@akira28 the css come from husky. this is in the adminbundle to fix or change something in husky you need also an PR in https://github.com/massiveart/husky.

**Comment by akira28** [comment]
Done! https://github.com/massiveart/husky/pull/665
Should I submit the js dist file? Also, do you have a list of functionalities using the overlay?

**Comment by wachterjohannes** [comment]
@akira28 what do you mean wth functionalities? the overlay is a quite simple component which can have multiple slides and buttons.

**Comment by akira28** [comment]
@wachterjohannes I mean, is this overlay just used by "copy" and "move" actions? Thing is I don't want to break other parts of the admin panel. Anyway in this PR the default behavior is to not show the webspace node, and show it just when copying and moving, so in theory it shouldn't break anything.
Let me know if I should commit the modified compiled dist js file.

**Comment by wachterjohannes** [comment]
@akira28 no i think this change should only effect the copy and move. you can push the dist files and i will test it locally. Please also not forget to add a line in the changelog. Then this PR is ready.

**Comment by akira28** [comment]
I'm going to squash the commits, to make it clean

**Comment by akira28** [comment]
Just found out you can do it much faster: https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by akira28** [comment]
Do I need to do something else to get this approved and merged?

**Comment by wachterjohannes** [comment]
merged with https://github.com/sulu/sulu/commit/39fb7a43d38592e04fb08bdbe5cf0ceef2403731

**Comment by wachterjohannes** [comment]
@akira28 sorry for the delay but we are currently quite busy.

**Pull request closed without merging**
