### PR TITLE
Bumped twig version to ^1.11

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR bumps version of twig to `^1.11`

### CODE REVIEW

**Comment by danrot** [comment]
@wachterjohannes Can you please add the same fix in appveyor as for #3126?

**Comment by wachterjohannes** [comment]
@danrot done

**Comment by danrot** [comment]
@wachterjohannes Seems like you also need the version restriction on php here, as on the develop branch.

**Comment by wachterjohannes** [comment]
@danrot done (:

**Pull request merged**
