### PR TITLE
Remove deprecation message from getcolspan on section

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

Remove deprecation message from getcolspan on section.

#### Why?

Sections can have colspan in sulu 2.0.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@danrot ok now i'm little bit confused about this deprecations as this function are still used and are spaming the log in my case when editing pages. How we can ride of them or should the functions stay?

**Comment by danrot** [comment]
IIRC we decided to rename it to `getSize`, and this method should be used instead.

**Comment by danrot** [comment]
@alexander-schranz Maybe we can fix the deprecation message to tell that `getSize` and `setSize` should be used instead? Or we could remove it all together, or doesn't that work yet?

**Comment by alexander-schranz** [comment]
@danrot I can have a look at it maybe later, but I'm not sure if size is good choice for a value which only represent the width of the element which value is neither pixels or percents of the parent.
Colspan did represent it for me better what it does as size.

/cc @chirimoya

**Comment by danrot** [comment]
`colspan` indicates to me that there should also be a `rowspan`, which is not the case... But I am not really sure if that was the real reason for this change.

**Comment by danrot** [comment]
Replaced by #4459

**Pull request closed without merging**
