### PR TITLE
Avoid exceptions in media serialization when not all data is loaded

### LINKED ISSUE #2595: Media throws runtime exception on serialize when no collection was join
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.2

#### Actual Behavior

When the collection is not joint in a query and serialize the Media it will throw an exception 
`Media entity %d is not associated with a collection`.

#### Expected Behavior

The getCollection should not throw a RuntimeException.

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixes | fixes #2595 
| License | MIT

#### What's in this PR?

Do not throw a runtime exception when the media collection is not loaded.
And initialize to-many items as array because doctrine dont call construct.

#### Why?

When you only want to load specific data of a media and use the media api entity to get the thumbnail urls it will throw a runtimeexception when the collection was not joined. 

Also all to-many relations are set as array because doctrine use reflection to set the data so the construct is not called when there is no lazy loaded entity.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@danrot I'm not sure why this exception was added? https://github.com/alexander-schranz/sulu/commit/6c43501a52f8af54a89974463a926e27f3d1d2a4

**Comment by chirimoya** [comment]
Test failing. Please have a look.

**Comment by alexander-schranz** [comment]
@chirimoya i removed the test as it is not longer needed.

**Comment by alexander-schranz** [comment]
@danrot branch is rebased

**Pull request merged**
