### PR TITLE
SecuritySubscriber throws exception when User is not an instance of UserInterface

### LINKED ISSUE #3389: Sulu SecuritySubscriber should not throw exception when User is not an instance of UserInterface
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.4

#### Actual Behavior

The Sulu SecuritySubscriber throws an error when the user is not an instance of `Sulu\Component\Security\Authentication\UserInterface`. As far as I can tell, this prevents one from using a custom user provider on a secured route (where the site has tokenStorage).

I our case, this prevents us from using the Symfony LDAP component to authenticate users to the web front end.

#### Expected Behavior

SecuritySubscriber should return null instead of throw an exception when the user does not implement the Sulu UserInterface.

https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/DocumentManagerBundle/Document/Subscriber/SecuritySubscriber.php#L70

### PR DESCRIPTION
**Pull request by cdesign**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3389
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Addresses this issue [#3389](https://github.com/sulu/sulu/issues/3389)

SecuritySubscriber currently throws an error when the user is not an instance of Sulu\Component\Security\Authentication\UserInterface. As far as I can tell, this prevents one from using a custom user provider on a secured route (where the site has tokenStorage).

This change solved our specific problem: using Symfony LDAP component to authenticate various custom routes.

### CODE REVIEW

**Comment by danrot** [comment]
Thanks for your contribution! But a few remarks:

1. Please also add a line in the `CHANGELOG.md` file explaining what it does and what the number of the PR is. 
2. We also have a column in our PR template for the issue being fixed, I've added the issue there for you.
3. The tests are failing. I would suggest that you rename and change the test accordingly (instead of checking if an exception has been thrown it should be checked if `null` is returned now.

**Comment by cdesign** [comment]
Daniel..

Very sorry. As you can tell, I'm somewhat new to github. So thank you for your patience :)

I now see that I was a bit lazy and should have read [this](http://docs.sulu.io/en/latest/developer/contributing/pull-requests.html) first. I will follow those steps from now on. As for this PR, would it be best to just close it and start over? Or can I somehow rebase it thru github?

And I think I have the test working. However, you suggested changing the name from `testSetDefaultUserWithNonSuluUser`. What should it be? That kind of seems appropriate to me as it is.

**Comment by danrot** [comment]
Did you make all of these changes in the Github UI? That's not really the way to go, since it is hard to test your changes this way... You actually should check out the code locally, so that you can work on it. Then you can also do rebasing and that kind of stuff. I think it is not possible to rebase via the Github UI...

And you don't seem to have touched the test... I think I will create a PR on my own for this bug, because we want to do a release soon... In the mean time I would suggest you inform yourself more about git (can recommend [this book](https://git-scm.com/book/en/v1)) so that you can do the next PR  on your own 😃

**Comment by danrot** [comment]
Replaced by #3404.

**Comment by danrot** [comment]
Also, for the future you should set the PR to the correct branch. Your code should go into the `master` branch, because I suppose you want it to be a hotfix. The master branch will be the place for hotfixes, and the next release from the master branch will be 1.5.5, whereby the `develop` branch will result in the new 1.6 release, which also comes with new features.

**Pull request closed without merging**
