### PR TITLE
Fixing PostgreSQL support

### LINKED ISSUE #53: Date format
Date should be formatted and internationalized to be shown in datagrid

### PR DESCRIPTION
**Pull request by danrot**
This branch is activating the build for PostgreSQL, which is currently failing. @carltongibson will create some Pull Requests targeted at this branch to fix this.

__tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #53
| BC breaks        | hopefully none
| Documentation PR | none

### CODE REVIEW

**Comment by carltongibson** [comment]
**Update:**

Of the originally failing bundles, we're about half way there. #1720, #1725, #1726 fixes Categories, Contacts and Tags respectively. (@danrot: please review at your leisure.)

I have to pause until next week now but I will continue with `MediaBundle`. The queries here are more complex but, it is exhibiting the same _semi-random_ failures as I found in #1725. 

Here's one run:

```
.............F.....F..................................F.F......  63 / 108 ( 58%)
.............................................
```

And here's another one straight after: 

```
.................................................F..FF.F.F.....  63 / 108 ( 58%)
.............................................
```

Same tests. Different failures. :-) Again it'll just be a case of providing Postgres with the correct ordering. (There is an `$orderBy` parameter being passed around so I need to see exactly what's happening to that but I'm assuming it'll be a single change in the end.)

Having got this far without incident I'm optimistic that `ResourcesBundle` and `SecurityBundle` will prove relatively easy to resolve as well. (I haven't yet looked)

**Comment by danrot** [comment]
@carltongibson The progress already looks quite good, there aren't too many failing tests left. However, it would be good if we don't wait too long on finishing this, I've already seen a new feature failing some tests again :confused:

**Comment by carltongibson** [comment]
@danrot Yeah — I didn't think I was far off. IIRC there were remaining ordering issues — with intermittent failures and that was about it. 

(I thought ordering the relations __may__ be all that's needed there — but didn't get to check that.)

Will say more in Feb! Ping me on anything relevant so I can keep up.

**Comment by danrot** [comment]
Replaced by #2703

**Pull request closed without merging**
