### PR TITLE
Remove mime_content_type from formatManager

### LINKED ISSUE #1153: Remove mime_content_type from FormatManager
Remove ```mime_content_type``` from ```sulu/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php``` as it is deprecated. @alexander-schranz suggested to use ```getMimeType``` of ```Symfony\Component\HttpFoundation\File\File``` instead.

### PR DESCRIPTION
**Pull request by alexander-schranz**
**Tasks:**
- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] added changelog line

**Informations:**

| Q | A |
| --- | --- |
| Tests pass? | none |
| Fixed tickets | fixes #1153 |
| BC Breaks | none |
| Doc | none |

### CODE REVIEW

**Comment by alexander-schranz** [comment]
I added fileinfo as requirement else getMimeType() would through an exception when the PHP Extension is not installed. /cc @chirimoya @danrot

**Comment by sabinebaer** [comment]
@alexander-schranz Regarding the dependency: Symfony gave me the following message on an IIS without the fileinfo extension: 
```Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)```

However, I am not sure if ```Symfony\Component\HttpFoundation\File\File```needs the ```fileinfo``` extension anyway or if they could use other methods to guess the mime type as well (I think Symfony would have added it to their dependencies if so?).

**Comment by alexander-schranz** [comment]
I think symfony never requires extensions(https://github.com/symfony/HttpFoundation/blob/master/composer.json) they only throw exceptions when an extension is not enabled.

**Comment by dilipom13** [comment]
Hello Sir,

https://prnt.sc/1qtg47a

**error** : **Unable to guess the MIME type as no guessers are available (have you enabled the php_fileinfo extension?).**

I face above error, I add the 'extension = fileinfo' and 'extension=php_fileinfo.dll' in php.ini (in cPanel).
but can't resolve this error, please help me.

**Pull request merged**
