### PR TITLE
Set default locale for admin user to "en".

### PR DESCRIPTION
**Pull request by ADmad**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

Set default locale for admin user to "en".

#### Why?

This is more friendlier to international users.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
can you add a line to the CHANGELOG.md for `dev-master`

**Comment by ADmad** [comment]
> can you add a line to the CHANGELOG.md for * dev-master

Sorry, my interest only lies in Sulu 2.0 and I don't want to spend time of updates for 1.x. I opened this PR targeting `master` only since you requested it and was a trivial fix.

> I updated the PR description please use the PR template next time.

Sorry about that, will take care in future.

**Comment by danrot** [comment]
@alexander-schranz Did you take over this PR? Can you rebase it? I think one of the errors is already fixed.

**Comment by alexander-schranz** [comment]
@danrot rebased to 1.5

**Pull request merged**
