### PR TITLE
Fix deprecations to be compatible to twig2

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes deprecations to be compatible to twig2.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@chirimoya @danrot should we introduce this as hotfix release? when not we should add a constraint for twig in the sulu/sulu repo (1.4 maybe also 1.3, 1.2, ...)?

**Comment by danrot** [comment]
@wachterjohannes I am getting the following error with your branch checked out:
image

Seems to be an issue with the JMS Serializer, don't you get the same?

**Comment by wachterjohannes** [comment]
i currently want to post this exception also (: i think it is an error with the jms/serializer but in a newer version it seems to be fixed.

**Comment by danrot** [comment]
@wachterjohannes Can you fix it? Otherwise we probably can't support twig 2.0.

**Comment by wachterjohannes** [comment]
yes i will try to update serializer here.

**Comment by danrot** [comment]
There also seems to be a problem with the macro in the [WebspaceCollection template](https://github.com/sulu/sulu/blob/0503ae986dee52f5740fbe1ffae33aece6619b75/src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig#L78). The content there is just empty, which make the `sulu:build` command fail:

```
          [Symfony\Component\Debug\Exception\FatalThrowableError]
          Parse error: syntax error, unexpected ')'
```

**Comment by wachterjohannes** [comment]
@danrot fix was easy but tricky to find! the `_self` variable cannot be used directly in twig 2. therefor we have to import it. there was only one file in sulu which uses this var directly. i have also fixed it there.

**Comment by danrot** [comment]
Great, it is working so far. Would be great if you could fix the Appveyor tests (there is some error with the checksum, the test outputs how to fix that).

One question remains, shouldn't we keep the twig version to 1.x for the existing releases, and add the rule to allow 2.0 in Sulu 1.5? Then these breaking changes on twig would at least not happen before a Sulu update. /cc @chirimoya

**Comment by danrot** [comment]
Discussed the version question with @chirimoya yesterday, we go only for twig 1.x in Sulu 1.3 and 1.4, and allow it to update (using the `||` in composer) on Sulu 1.5. We should probably also mention that in the `UPGRADE.md`.

**Comment by wachterjohannes** [comment]
@danrot this is now ready to merge it to develop.

**Comment by danrot** [comment]
@wachterjohannes Tests are failing for PHP 7.0

**Comment by danrot** [comment]
@wachterjohannes Now I get the following error when accessing the website:
image

The request for the web developer toolbar is failing. I also tried clearing the cache, didn't help.

**Pull request merged**
