### PR TITLE
Feature Sulu Snippet Load By Type

### PR DESCRIPTION
**Pull request by codebarista**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#376

#### What's in this PR?

A twig extension to load all snippets of a given type.

#### Why?

We use this to let a content editor edit and translate our React app contents.

#### Example Usage

~~~twig
        {% set snippets = sulu_snippet_load_by_type('foo') %}
        <script>
            window.translations = {
            {% for snippet in snippets %}
                {{ snippet.key }}:'{{ snippet.title }}'{{ not loop.last ? ','}}
            {% endfor %}
            }
        </script>
~~~

### CODE REVIEW

**Comment by trickreich** [comment]
Hey @codebarista 
Thanks for the contribution! :smile: 

You've implemented this extension for develop? Or should the target be the master branch?

**Comment by codebarista** [comment]
Hey @trickreich, of course, the target should be the master branch. 😄

**Comment by wachterjohannes** [comment]
@codebarista you should be able to change the target and rebase the branch - the functionality looks good to me, after testing on the master we could take a deeper look into it @danrot what do you think?

**Comment by codebarista** [comment]
@wachterjohannes Rebasing had a bunch of conflicts, so I'm going to pull the feature in a new branch.

**Pull request closed without merging**
