### PR TITLE
Export text of webspace as XLIFF

### PR DESCRIPTION
**Pull request by alexander-schranz**
__Tasks:__

- [x] test coverage
- [ ] gather feedback for my changes
- [x] submit changes to the documentation
- [x] added changelog line
- [x] Missing Fields:
  - [x] Navigation Context
  - [x] Published
  - [x] Created
  - [x] Changed
  - [x] Creator
  - [x] Changer
  - [x] Permissions
  - [x] Shadow Locale
  - [x] RedirectExternal
  - [x] RedirectType
  - [x] WorkflowStage

__Informations:__

| Q             | A
| ------------- | ---
| Fixed tickets | part of #1686
| BC Breaks     | yes
| Doc           | https://github.com/sulu-io/sulu-docs/pull/123

e.g. commands

``` bash
app/console sulu:webspace:export -w sulu_io -l de test.xliff 
# or only specific page
app/console sulu:webspace:export -w sulu_io -l de test.xliff -u 6f7b92c1-81a3-424d-97a6-95728f217fa1
```

### CODE REVIEW

**Comment by chirimoya** [comment]
@alexander-schranz @c00n84 if relevant for version 1.1 please finish PR.

**Comment by alexander-schranz** [comment]
Currently some fields are missing in the export add them to the requirements.

**Comment by webmozart** [comment]
@alexander-schranz What's the status here?

**Comment by alexander-schranz** [comment]
@webmozart did work at the weekend at this PR. will finish the tests soon and will rebase then and continue to implement the missing things in #1758 which is based on this branch.

**Pull request closed without merging**
