### PR TITLE
Prevented LogicException when accessing media due to analytics listener

### LINKED ISSUE #3745: LogicException when accessing media due to analytics listener
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13
| Browser Version | Chromium v63.0.3239.132 (Official Build) Built on Ubuntu, running on Ubuntu 14.04 (64-bit)

#### Actual Behavior

```
LogicException:
The content cannot be set on a BinaryFileResponse instance.

  at vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php:323
  at Symfony\Component\HttpFoundation\BinaryFileResponse->setContent(false)
     (vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php:119)
  at Sulu\Bundle\WebsiteBundle\EventListener\AppendAnalyticsListener->onResponse(object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
  at call_user_func(array(object(AppendAnalyticsListener), 'onResponse'), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:104)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(FilterResponseEvent), 'kernel.response', object(ContainerAwareEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:191)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(BinaryFileResponse), object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:173)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/website.php:41)
```

#### Expected Behavior

BinaryFileResponse is returned without exception.

#### Steps to Reproduce

1. Open admin interface.

2. Open Media.

3. Upload an SVG file.

4. Create any page with `media_selection` property.

5. Select SVG media from step 3.

6. In page template, use ``, which will output url for master file: `/media/199/download/parking-scheme.svg?v=1`

7. SVG is not returned due to `LogicException`.

### PR DESCRIPTION
**Pull request by gram7gram**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3745 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

### CODE REVIEW

**Comment by danrot** [comment]
Thanks for your contribution! Do you know if this error is also happening on version 1.5.x? Then we should fix it there. And there is also a `CHANGELOG.md` in the 1.x series, where a line should be added.

**Comment by danrot** [comment]
Oh, and before I forget, there should also be a test for that :smiley:

**Comment by gram7gram** [comment]
Right. I forgot the PR are not that easy... I will find time to complete PR

**Comment by gram7gram** [comment]
I was not able to launch a project with sulu, so I have forgotten about the PR. I will not finish it. Close it, if you do not need it.

**Pull request closed without merging**
