### PR TITLE
Added exception handling for preview-renderer

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | fixes the comment for PR https://github.com/sulu/sulu/pull/2299#discussion_r60886161
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR adds own exceptions and error-templates for different issues when rendering a preview.

pasted image at 2016_04_25 11_35 am

#### Why?

To show the user whats happen.

#### To Do

- [x] Tests
- [x] Exception handling for rendering
- [x] Javascript
- [x] Translations fr (waiting)

**Translations:**

* L’aperçu n’est pas disponible
* N’aucun RouteDefaultsProvider trouvé.
* S’il te plaît modifie webspace

### CODE REVIEW

**Comment by chirimoya** [comment]
Missing `ObjectProviderNotFoundException`

**Comment by wachterjohannes** [comment]
@chirimoya i have added a `ObjectProvider` exception message.

**Comment by chirimoya** [comment]
@wachterjohannes rebase

**Comment by wachterjohannes** [comment]
@chirimoya done

**Pull request merged**
