### PR TITLE
Check domain when creating an internal redirect

### LINKED ISSUE #5467: No URL generated for internal links from different webspaces
| Q | A
| --- | ---
| Sulu Version | 1.6.35
| Browser Version | All browsers

# Actual Behavior

When adding internal links in a texteditor, url's for pages on a different webspace are not generated correctly. The `<a>` tag is rendered without an `href` for these pages. Url's for pages on the same webspace _are_ generated correctly.

# Expected Behavior

The links to pages on different webspaces should be rendered with an href.

# Steps to Reproduce

1. Create a field with a texteditor type
2. In the texteditor field, add an internal Sulu link to a page on a different webspace
3. The link is rendered without an `href` 

# Possible Solutions

As discussed in Slack, this seems to be a bug in the `findUrlByResourceLocator` method called here
https://github.com/sulu/sulu/blob/f8a39a228ca763607ba7e9743f3af7b3397be51f/src/Sulu/Bundle/ContentBundle/Markup/Link/PageLinkProvider.php#L111

When `$domain` is set to `null` the url is generated correctly.

### PR DESCRIPTION
**Pull request by jaimybroere**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5467
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | ---

#### What's in this PR?

Create a working redirect for internal links to pages on another webspace.

### CODE REVIEW

**Comment by nnatter** [comment]
@sulu/core-team I think this is something that should be included in the next release. Does anybody understand why this changes break the `SitemapControllerTest `? 🤔

**Comment by danrot** [comment]
Haven't had a closer look at the sitemap tests, but I think there is something wrong with that implementation... There is also a currently failing test in the `WebspaceManagerTest`, and I would say the test is correct (it should be `sulu.at/test`) :confused:

**Comment by nnatter** [comment]
Is this ready for review? 🙂

**Review by niklasnatter — APPROVED** [review]

**Comment by nnatter** [comment]
Thanks for working on this!

**Pull request merged**
