### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by gisostallenberg**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | n/a
| Related issues/PRs | #1905
| License | MIT
| Documentation PR | n/a

#### What's in this PR?

The Dutch translation of the admin interface.

#### Why?

Because it is cool to have Sulu in Dutch.
I will create a tool to see what source-tags are in a base file compared to the target file and keep track on your development branch, but please do not hesitate to contact me for a translation when needed.

#### Example Usage

n/a

### CODE REVIEW

**Comment by danrot** [comment]
I think you are missing some updates [here](https://github.com/sulu/sulu/blob/d91770748cd079a892f905bfe44472e13671abbe/src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php#L63) and [here](https://github.com/sulu/sulu/blob/d91770748cd079a892f905bfe44472e13671abbe/src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php#L67), so that this actually turns up in the dropdown 😃

**Comment by danrot** [comment]
And according to my output you have translated a little bit too much 😉 

``` bash
 ~/Development/massiveart/sulu-standard $ sf sulu:translate:export
Exported 807 translations to web/admin/translations for locale de
Exported 807 translations to web/admin/translations for locale en
Exported 807 translations to web/admin/translations for locale fr
Exported 811 translations to web/admin/translations for locale nl
```

**Comment by danrot** [comment]
We should actually also get rid of these settings in [sulu-standard](https://github.com/sulu/sulu-standard/blob/2145806de11e2bbe120b6585b3f3f72ee28bd790/app/config/sulu.yml#L63), because they are simply redefined with the same values... I can do that once you've adapted the rest.

**Comment by gisostallenberg** [comment]
@danrot Removed the excessive translations, and added the dropdown info.

**Comment by danrot** [comment]
Great, thank you 😃

**Pull request merged**
