### PR TITLE
Run preview cache clear command only when App\Kernel exists

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes -
| Related issues/PRs | #4782
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Aslong the PreviewKernel extends from App\Kernel we need to check in this listener if `App\Kernel` exist and only then allow to clear also the preview cache.

This lines can be removed when https://github.com/sulu/sulu/issues/4782 is fixed.

#### Why?

Currently all bundles with use of `cache:warmup` to generate data for phpstan crash because they don't have a App\Kernel in it.

### CODE REVIEW

**Comment by danrot** [comment]
Do I get this right: This is required to silent phpstan? What is the exact error it throws? This check feels a bit weird to me at this place... Shouldn't this cause an error already when trying to extend `\App\Kernel` if it does not exist?

**Comment by alexander-schranz** [comment]
@danrot no you misunderstand it. Its not phpstan throwing an error.

If you use the [phpstan symfony plugin](https://github.com/phpstan/phpstan-symfony) you need to run `bin/console cache:clear` that the `container.xml` is generated. But as most bundles doesn't have a `App\Kernel` it will throw an error when it nows try to also clear/warmup the Preview cache.

**Comment by danrot** [comment]
Can you maybe give me an example of a bundle where I can test this?

**Comment by alexander-schranz** [comment]
@danrot ArticleBundle or FormBundle it seems only fail `dump-autoload --optimize` was called:

```
composer create-project sulu/form-bundle:dev-master --keep-vcs
cd vendor/sulu/sulu/
git fetch origin
git checkout origin/release/2.0
cd ../../..
composer dump-autoload -o
Tests/Application/bin/adminconsole cache:clear
```

**Pull request merged**
