### PR TITLE
WIP: Add custom media storage

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | built ontop #4321  
| License | MIT
| Documentation PR | TODO

#### What's in this PR?

This PR add custom media storage.

#### Why?

This can be used to upload media to a custom storage.

- [ ] Create a documentation PR

### CODE REVIEW

**Comment by danrot** [comment]
@wachterjohannes Do we still need that, or can it be closed?

**Comment by wachterjohannes** [comment]
@danrot i think we need something like that - but i am not happy with it currently have to think about it!

**Comment by nnatter** [comment]
@wachterjohannes is this still relevant?

**Comment by nnatter** [comment]
Closing this due to inactivity 🙂

**Pull request closed without merging**
