### PR TITLE
Add Flysystem 3 storage implementation

### LINKED ISSUE #5701: Add Flysystem V2 Support
| Q | A
| --- | ---
| Sulu Version | 2.2
| Browser Version | Browser name and version

# Actual Behavior

When I configure S3 as external media storage, I get the following error on the cli:
`Unrecognized option "s3" under "sulu_media.storages". Available option is "local".`

# Expected Behavior

Sulu should recognize the configuration

# Steps to Reproduce

I followed the docs: https://docs.sulu.io/en/2.2/cookbook/external-media-storage.html
* Installed the packages flysystem and flysystem-aws-s3-v3
* Added the configuration yaml-snippet

# Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no  
| Fixed tickets | fixes #5701
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Add Flysystem 3 storage implementation.

#### Why?

Support different Flysystem Adapter v3 without changing the `StorageInterface`.

#### To Do

- [ ] Remove `AzureBlobStorage`
- [ ] Remove `S3Storage`
- [ ] Remove `GoogleCloudStorage`
- [ ] Remove storage specific configurations `sulu_media.storages.*`
- [ ] Add new configuration `sulu_media.storages.flysystem.service: 'default.storage'`
- [ ] `FlysystemStorage` should not longer be `abstract`
- [ ] `FlysystemStorage` implement getPath (flysystem 3 has getDownloadUrl) return still path if LocalStorage is used
- [ ] `FlysystemStorage` implement getType (Local) returns `TYPE_REMOTE`, `TYPE_LOCAL`
- [ ] Remove own `LocalStorage` will be replaced FlysystemStorage
- [ ] Add flysystem configuration:

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads'
 ```

### CODE REVIEW

**Comment by mamazu** [comment]
I'm currently working on it and I have a few questions:
1. I can't find any method called `getDownloadUrl` there is a way to generate public urls but this would require changing the interface because it requires a file name.
2. Flysystem in itself doesn't have a config like you mentioned in the last item. Should this be part of the media bundle as well? Or just a service definition?

**Comment by alexander-schranz** [comment]
@mamazu all data required to get path and url are there already. You get the filebame from the storageoptions same as the directory (segment): https://github.com/sulu/sulu/blob/122b64644f80f39142c29811d1acca5f9ffc8463/src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php#L76

**Comment by alexander-schranz** [comment]
@mamazu the config comes from the flysystem bundle: https://github.com/symfony/recipes/blob/b06f1ce2f7c3f7d5cb18fcce68c08a02cc1b271c/league/flysystem-bundle/1.0/config/packages/flysystem.yaml#L4

**Comment by mamazu** [comment]
This PR can probably closed as #7687 will be merged.

**Pull request closed without merging**
