### PR TITLE
Added root kernel path to be available as document data fixtures paths

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

Added root kernel path to be available as document data fixtures paths.

#### Why?

As the src folder is not longer a bundle we need to add `src/DataFixtures/Document` as data fixture folder. 

#### Example Usage

~~~php
<?php

// src/DataFixtures/Document/PageFixture.php

namespace App\DataFixtures\Document;

use Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentFixtureInterface;
use Sulu\Component\DocumentManager\DocumentManager;

class PageFixture implements DocumentFixtureInterface
{
    public function getOrder()
    {
        return 10;
    }

    public function load(DocumentManager $documentManager)
    {
        // ...
    }
}
~~~

### CODE REVIEW

**Comment by alexander-schranz** [comment]
ping @danrot

**Comment by danrot** [comment]
Didn't work when I was trying to test it, but I guess that's because this PR is not rebased.

**Comment by alexander-schranz** [comment]
@danrot is rebased

**Comment by danrot** [comment]
Tests are failing quite strange, doesn't feel like it is caused by this test... Will merge it anyway, and hope that it fixes itself :see_no_evil:

**Pull request merged**
