### PR TITLE
Renamed parameters.yml to parameters.yml.dist so you can use a local …

### PR DESCRIPTION
**Pull request by kfrohwein**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | None

#### What's in this PR?

I want to use a local database configuration for testing. This was currently not possible. So moved the parameters.yml to parameters.yml.dist as a default and added a check if there is parameters.yml or not. If there is one the local version will be used. If not the one distributed with sulu/sulu.

#### Example Usage
Copy the `sulu/sulu/src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml.dist` file to parameters.yml and do your changes.

#### To Do

Add this to the common documentation.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@kfrohwein could you please add a line in the `CHANGELOG.md`? and please also update your branch. after that i can merge this.

**Comment by wachterjohannes** [comment]
@kfrohwein please add a changelog line for this PR after that i could merge it

**Comment by kfrohwein** [comment]
Sorry but I have no clue why the appveyor check failed as I don't see any log...

**Comment by wachterjohannes** [comment]
@kfrohwein do you have fetched from sulu/sulu repo before update branch?

**Pull request merged**
