### PR TITLE
added and used config for vendor directory from composer.json

### PR DESCRIPTION
**Pull request by danrot**
This PR tries to replace the hard coded paths to the vendor directory in the config files. Sadly the configuration is resolved too early in https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php#L36, and we can't use a variable introduced in a compiler pass because of that.

**tasks:**
- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation

**informations:**

| q | a |
| --- | --- |
| Fixed tickets | fixes https://github.com/sulu-io/sulu-standard/issues/542 |
| BC breaks | none |
| Documentation PR | TODO |

### CODE REVIEW

**Comment by patkar** [comment]
Is this maybe possible in the `prepend()` of the `SuluCoreExtension` class? (needs to implement `PrependExtensionInterface`)

**Comment by danrot** [comment]
Yeah, the line I have linked in the description is in this method :wink:

**Comment by patkar** [comment]
Upsi. Didn't look accurately

**Comment by wachterjohannes** [comment]
@danrot should this be included in 1.1?

**Comment by danrot** [comment]
Would be nice, but it is currently not working, and I don't have the time to finish it...

**Pull request closed without merging**
