### PR TITLE
Fix localizations for the TemplateAttributeResolver

### LINKED ISSUE #5697: The "localizations" entry is not always available in the templates
| Q | A
| --- | ---
| Sulu Version | 2.2.2
| Browser Version | Firefox Linux

# Actual Behavior

Sulu should provide a "localizations" variable in each templates.
It does not provide it for templates rendered from custom controller, instead there is a "urls" variable which seems deprecated.

# Expected Behavior

The "localizations" variable should be available in all the templates.

# Steps to Reproduce

Configure a sulu with at least 2 locales. The "localizations" variable is available in the default base template.
Create a custom controller and render a custom template which extends the base template. There is only an "urls" variable available.
My custom controller is based on:
https://github.com/sulu/sulu-workshop/blob/master/src/Controller/Website/EventWebsiteController.php

# Possible Solutions

Seems confirmed by users niklas and alex in Slack.
Comment from "niklas": "it looks like the TemplateAttributeResolver was not updated when deprecating the urls variable"

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5697
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Add handling for `urls` and `loclzations` to the `TemplateAttributeResolver` which handles static routes.

#### Why?

It should have the same behaviour as the ParameterResolver which handles dynamic structure routes.

### CODE REVIEW

**Review by nnatter — APPROVED** [review]

**Comment by nnatter** [comment]
@alexander-schranz I changed this a bit to trigger a deprecation message to be consistent with: https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php

Is the change okay for you?

**Comment by alexander-schranz** [comment]
Did change the behaviour when the urls are set from outside but okay for me this way.

**Review by nnatter — APPROVED** [review]

**Comment by danakil** [comment]
I just tested this PR and it seems to resolve the issue #5697

**Comment by alexander-schranz** [comment]
@danakil Thank you for testing!

**Pull request merged**
