### PR TITLE
Export text of webspace as XLIFF

### PR DESCRIPTION
**Pull request by alexander-schranz**
Moved from #1695 

__Tasks:__

- [x] test coverage
- [ ] gather feedback for my changes
- [x] rebase
- [x] submit changes to the documentation
- [x] added changelog line
- [x] Missing Fields:
  - [x] Navigation Context
  - [x] Published
  - [x] Created
  - [x] Changed
  - [x] Creator
  - [x] Changer
  - [x] Permissions
  - [x] Shadow Locale
  - [x] RedirectExternal
  - [x] RedirectType
  - [x] RedirectTarget
  - [x] WorkflowStage

__Informations:__

| Q             | A
| ------------- | ---
| Fixed tickets | part of #1686
| BC Breaks     | yes
| Doc           | https://github.com/sulu-io/sulu-docs/pull/123

e.g. commands

``` bash
app/console sulu:webspace:export -w sulu_io -l de test.xliff 
# or only specific page
app/console sulu:webspace:export -w sulu_io -l de test.xliff -u 6f7b92c1-81a3-424d-97a6-95728f217fa1
```

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@sulu/core-team don't know why the components test fail at PHP7.

**Comment by danrot** [comment]
@alexander-schranz Hm, I restarted the build for now... This PR was created some time ago, wasn't it? Did you rebase?

**Comment by alexander-schranz** [comment]
@danrot yes did rebased. The #1695 was the original PR.

**Comment by alexander-schranz** [comment]
new PR: #2705

**Pull request closed without merging**
