### PR TITLE
Fixes JS error when translations are empty.

### PR DESCRIPTION
**Pull request by Warxcell**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | 
| Related issues/PRs | 
| License | MIT
| Documentation PR | 

#### Why?

Requester.js:128 Uncaught (in promise) Error: Response was expected to be an object, but an array was given

### CODE REVIEW

**Comment by Warxcell** [comment]
According to https://www.php-fig.org/psr/psr-2/#6-closures my format seems ok.

**Comment by alexander-schranz** [comment]
@Warxcell can we split the code style errors in a seperate Pull Request we need to find a rule to lint that, but would still be good to merge the bugfix as soon as possible.

**Comment by Warxcell** [comment]
Done.

**Comment by alexander-schranz** [comment]
@Warxcell thank you for fixing this!

**Pull request merged**
