### PR TITLE
Add content resolver for the new ContentBundle architecture

### PR DESCRIPTION
**Pull request by Prokyonn**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes # 
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Adds new `PropertyResolver` and `ResourceLoader` to use for the `ContentBundle`

#### Why?

ContentBundle will introduce a new architecture to more efficiently resolve content.

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

### CODE REVIEW

**Comment by alexander-schranz** [comment]
As discussed with @Prokyonn teaser and link content type are a bit differently. But we said that we will go with a `LinkLoader` and `TeaserLoader` and so a special "link" and "teaser" resource, that way we don't require a lot of changes for teaser provider and link providers and can keep them currently as they are. But all teasers and links should be loaded via one query per type that way.

**Comment by alexander-schranz** [comment]
@Prokyonn for the PropertyResolvers inside bundle I would remove the `Resolver` namespace think `PropertyResolver` is enough. For ContentBundle it make sense to have that namespace for implementation I would skip it. What do you think?

```diff
-Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\Resolver\AccountSelectionPropertyResolver
+Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\AccountSelectionPropertyResolver
```

**Comment by Prokyonn** [comment]
> @Prokyonn for the PropertyResolvers inside bundle I would remove the `Resolver` namespace think `PropertyResolver` is enough. For ContentBundle it make sense to have that namespace for implementation I would skip it. What do you think?
> 
> ```diff
> -Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\Resolver\AccountSelectionPropertyResolver
> +Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\AccountSelectionPropertyResolver
> ```

Yes that totally makes sense 👍

**Comment by mamazu** [comment]
Just as a random thought. Could you also design the system so that it is easy to profile and debug these functions simmilar to the `DocumentManager/DebugEventDispatcher`?

**Comment by alexander-schranz** [comment]
@mamazu as now all are service tags it is straight forward over the `debug:container` now:

 - Get All property resolvers: `bin/console debug:container --tag sulu_content.property_resolver`
 - Get All resource loaders: `bin/console debug:container --tag sulu_content.resource_loader`

**Comment by alexander-schranz** [comment]
As discussed we will target the 3.0 for the new resolver and merge other bundles into that branch for easier maintainance, but that will be its own Pull requests.

**Comment by alexander-schranz** [comment]
Moved TODO list into own issue: https://github.com/sulu/sulu/issues/7672

**Pull request merged**
