### PR TITLE
Allow reference cascading when deleting tags

### PR DESCRIPTION
**Pull request by ymc-siwi**
See https://github.com/sulu/sulu/issues/6627

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #6672
| Related issues/PRs | none
| License | MIT

#### What's in this PR?

Will set on-delete="CASCADE" for tag references to accounts and contacts

#### Why?

Previous solution prevents deletion of referenced tags via backend; relations are not cleaned up properly if accounts or organizations are deleted.

For detailed description see https://github.com/sulu/sulu/issues/6627

#### To Do

- [ ] Create testcase
- [x] Add documentation for database change to UPGRADE.md

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Thank you for the pull request can you update also the other many to many relations so we don't run there in the same problems:

- https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml#L26-L33
- https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Group.orm.xml#L32-L41
- https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml#L86-L210
- https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml#L108-L234


For category keywords I'm not sure if needed but think it is also required there:

- https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml#L29-L30

**Comment by ymc-siwi** [comment]
@alexander-schranz Yes, makes sense - already done for se_group_roles. Would the following change be equal / favorable to `on-delete="CASCADE"` if a cascading tag is already defined for the regarding many-to-many field?
`<cascade> 
     <cascade-persist/> 
     <cascade-delete/> 
</cascade>`
Not sure if this has a functional impact or performance impact though. UnitOfWork should be the same as for cascade-persist...

**Comment by alexander-schranz** [comment]
The `on-delete="CASCADE"` has no impact on the PHP Performance as it is database only. And currently it would ended in a 500 error when you tried to remove a related entity and now it will just be savely removed.

The `<cascade>` itself I would currently not change in any entities as that would require a deeper discussion where it make sense and where not.

**Comment by alexander-schranz** [comment]
The failing Lint task you can currently ignore as it is not related to your Pull Request.

**Comment by ymc-siwi** [comment]
@alexander-schranz All done except category keywords. There is no blocking behavior when deleting categories/keywords/translations - all FK-relations already cascade or are set to null properly (no relation is defaulting to ON DELETE RESTRICT here). The change would only make sense for cleanup, but this could be addressed in another Pull Request.

**Comment by alexander-schranz** [comment]
@ymc-siwi Thank you, great work 👍

**Pull request merged**
