### PR TITLE
Added check for redirect-type-behaviour

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes a bug when you create an internal link to a unpublished pages.

#### Why?

This leads into an exception when loading this page inside the navigation.

### CODE REVIEW

**Comment by danrot** [comment]
Build is failing and a new test is missing :wink:

**Comment by wachterjohannes** [comment]
@danrot have rebased this branch - I think there is missing something. but there is no test setup for ContentMapper/NavigationMapper ... so its quite hard to test this small bug

**Comment by wachterjohannes** [comment]
@danrot the failing testcases are produced by symfony/symfony 3.4.16 (released this weekend).

The dumped (cached) service container is broken.

**Comment by wachterjohannes** [comment]
@danrot issue: https://github.com/symfony/symfony/issues/28658

**Comment by danrot** [comment]
Can you add a conflict then?

**Comment by wachterjohannes** [comment]
@danrot done

**Comment by alexander-schranz** [comment]
Closed because of incativity

**Pull request closed without merging**
