### PR TITLE
Added column definitions to resource-bundle

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes (it avoids a propably bug)
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | https://github.com/sulu/sulu-standard/pull/693
| License | MIT
| Documentation PR | none 

#### What's in this PR?

This PR adds column definitions for doctrine-orm entities. To avoid dropping of columns when naming-strategy will be changed. 

#### Why?

Doctrine drops columns which name is generated and recreate it if the naming-strategy was changed.

### CODE REVIEW

**Comment by danrot** [comment]
You have only updated 3 files here, but I have seen that there are 8 doctrine files in the ResourceBundle, whereby some of the others are also missing the column definition.

And you've also created this PR against develop, but when thinking about it this is probably right. This change should not be a hotfix, because people might easily lose information, because they don't expect to get some fields dropped on a hotfix release...

**Comment by wachterjohannes** [comment]
this is only necessary if you have camelCased field-names. i have only done it there.

**Comment by danrot** [comment]
Don't we usually add a column name in all the other bundles? For this reason I would also add the column attribute everywhere in these definitions.

**Comment by wachterjohannes** [comment]
@danrot fixed

**Comment by wachterjohannes** [comment]
@danrot wrong dest branch

**Comment by wachterjohannes** [comment]
closed in favor of https://github.com/sulu/sulu/pull/2382

**Pull request closed without merging**
