### PR TITLE
WIP: Added maximum-selection for media-selection

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes ???
| Related issues/PRs | https://github.com/massiveart/husky/pull/764
| License | MIT
| Documentation PR | TODO

#### What's in this PR?

This PR add the ability to set `maximumSelection` to media-selection

#### To Do

- [ ] Create a documentation PR

### CODE REVIEW

**Comment by alexander-schranz** [comment]
I would prefer to add the maxSelection to the datagrid or another general component so it can be reused for other content types. https://github.com/massiveart/husky/issues/704

**Comment by wachterjohannes** [comment]
we could add it there but the datagrid is such "messy" at this place - but could be easily portet.

**Comment by alexander-schranz** [comment]
would prefer to call it `limit` instead of maxSelection.

**Comment by wachterjohannes** [comment]
@danrot when do you think we can merge this? pre 1.5?

**Comment by danrot** [comment]
I would also move that to the datagrid, also if it might get a bit messy. Then the "messiness" is at least concentrated at one spot, and can be reused if necessary :-)

**Comment by danrot** [comment]
@wachterjohannes Will there be happening something on this PR, or can we close it?

**Comment by wachterjohannes** [comment]
@danrot to be honest :) i think we can close it ...

**Pull request closed without merging**
