### PR TITLE
Add test case for calling CsvHandler with CollectionRepresentation

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Related issues/PRs | #5223 
| License | MIT

#### What's in this PR?

This PR adds a test case for calling the CsvHandler with a CollectionRepresentation instance.

### CODE REVIEW

**Comment by danrot** [comment]
Tests are failing... It looks like something changed that made some rules ignorings in PHPStan unnecessary.

**Comment by alexander-schranz** [comment]
latest version of phpstan supports checking for `class_exists` correctly our `ignore_errors` for DoctrineCache and Vips should not longer be needed. @nnatter can you remove them.

**Comment by nnatter** [comment]
Yes, the handling of `class_exists()` was changed in 0.12.19, which was released 12 hours ago: https://github.com/phpstan/phpstan/releases/tag/0.12.19

Should I remove them in this PR?

Also, does the TravisCi Github integration work for you? I  just see a `Expected — Waiting for status to be reported` at the moment.

**Comment by danrot** [comment]
I checked in their online app. They had some maintenance today morning, probably related to that.

**Comment by alexander-schranz** [comment]
@nnatter remove them here. I think if you repush travis should be triggered correctly again.

**Comment by nnatter** [comment]
Okay looks like tests are only failing for branches based on the master branch. Tests are not failing for this PR:
https://travis-ci.org/github/sulu/sulu/builds/677155977

**Comment by danrot** [comment]
Okay, looks like I have checked the wrong test then :see_no_evil: Then we'll have to fix that in another PR.

**Pull request merged**
